version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - REACT_APP_SIGNALING_URL=http://localhost/signal
      
  signaling:
    image: node:16-alpine
    working_dir: /app
    expose:
      - "4000"
    volumes:
      - ./server:/app
    command: >
      sh -c "cd /app && 
             npm init -y && 
             npm install express socket.io cors ip &&
             node server.js"
    environment:
      - PORT=4000
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - signaling
